services:

  boltz:
    hostname: boltz
    depends_on:
      - lnd-2
    restart: always
    image: boltz/boltz:3.3.0
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/lnd-2:/data/lnd/
      - ./data/boltz/:/root/.boltz/

  bitcoind:
    hostname: bitcoind
    image: boltz/bitcoin-core:24.0.1
    command:
      - -regtest
      - -fallbackfee=0.00000253
      - -zmqpubrawtx=tcp://0.0.0.0:29000
      - -zmqpubrawblock=tcp://0.0.0.0:29001
      - -txindex
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=regtest
      - -rpcpassword=regtest
    expose:
      - 29000
      - 29001
      - 18443
      - 18444

  elementsd:
    hostname: elements
    image: ghcr.io/vulpemventures/elements:22.1.1
    expose:
      - 18884
      - 31000
      - 31001
      - 31002
    volumes:
      - ./data/elements:/home/elements/.elements

  clightning-1:
    hostname: clightning-1
    restart: always
    depends_on:
      - bitcoind
    image: boltz/c-lightning:22.11.1
    entrypoint: "lightningd --large-channels --network regtest --bind-addr=0.0.0.0:9735 --bitcoin-rpcconnect=bitcoind --bitcoin-rpcport=18443 --bitcoin-rpcuser=regtest --bitcoin-rpcpassword=regtest"
    expose:
      - 9735
    volumes:
      - ./data/clightning-1:/root/.lightning/

  lnd-1:
    hostname: lnd-1
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.5-beta
    restart: always
    entrypoint: "lnd --listen=lnd-1:9735 --rpclisten=lnd-1:10009 --restlisten=lnd-1:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=regtest --bitcoind.rpcpass=regtest --noseedbackup --protocol.wumbo-channels"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-1:/root/.lnd/

  lnd-2:
    hostname: lnd-2
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.5-beta
    restart: on-failure
    entrypoint: "lnd --listen=lnd-2:9735 --rpclisten=lnd-2:10009 --restlisten=lnd-2:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=regtest --bitcoind.rpcpass=regtest --noseedbackup --protocol.wumbo-channels"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-2:/root/.lnd/

  electrs:
    depends_on:
      - bitcoind
    restart: always
    hostname: electrs
    image: getumbrel/electrs:latest
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "regtest"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:18443"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:18444"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:50002"
    volumes:
      - ./data/electrs/:/data/.electrs/
    ports:
      - 50002:50002

  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    # image: vulpemventures/electrs
    restart: always
    hostname: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-rpc-addr
      - elementsd:18884
      - --cookie
      - regtest:regtest
      - --http-addr
      - 0.0.0.0:30001
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
      - --jsonrpc-import
      - -vvvv
    depends_on:
      - elementsd
    ports:
      - 50001:50001
      - 30001:30001

  mempool-web:
    restart: always
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: 8090
      BACKEND_MAINNET_HTTP_HOST: mempool-api
      BACKEND_MAINNET_HTTP_PORT: 8999
    image: mempool/frontend:latest
    ports:
      - 8090:8090

  mempool-api:
    hostname: mempool-api
    restart: always
    depends_on:
      - electrs
      - mempool-db
    image: mempool/backend:latest
    environment:
      MEMPOOL_HTTP_PORT: 8999
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: electrs
      ELECTRUM_PORT: 50002
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: 18443
      CORE_RPC_USERNAME: "regtest"
      CORE_RPC_PASSWORD: "regtest"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: mempool-db
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    ports:
      - 8999:8999

  mempool-web-liquid:
    restart: always
    depends_on:
      - mempool-api-liquid
    environment:
      BACKEND_MAINNET_HTTP_HOST: mempool-api-liquid
      BACKEND_MAINNET_HTTP_PORT: 8998
      FRONTEND_HTTP_PORT: 8091
      LIQUID_ENABLED: true
      BASE_MODULE: 'liquid'
    image: mempool/frontend:latest
    ports:
      - 8091:8091

  mempool-api-liquid:
    hostname: mempool-api-liquid
    restart: always
    depends_on:
      - electrs-liquid
      - mempool-db-liquid
    image: mempool/backend:latest
    environment:
      MEMPOOL_HTTP_PORT: 8998
      # MEMPOOL_API_URL_PREFIX: "/liquid/api/v1/"
      MEMPOOL_NETWORK: "liquid"
      MEMPOOL_BACKEND: "electrum"
      # ESPLORA_REST_API_URL: "http://electrs-liquid:30001"
      ELECTRUM_HOST: electrs-liquid
      ELECTRUM_PORT: 50001
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: elementsd
      CORE_RPC_PORT: 18884
      CORE_RPC_USERNAME: "regtest"
      CORE_RPC_PASSWORD: "regtest"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: mempool-db-liquid
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    ports:
      - 8998:8998

  mempool-db:
    hostname: mempool-db
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8

  mempool-db-liquid:
    hostname: mempool-db-liquid
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
