version: "3.7"
services:

  boltz:
    hostname: boltz
    depends_on:
      - lnd-2
    image: boltz/boltz:3.3.0
    entrypoint: "sh -c 'sleep 40; /boltz-backend/bin/boltzd'"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/lnd-2:/data/lnd/
      - ./data/boltz/:/root/.boltz/

  bitcoind:
    hostname: bitcoind
    image: boltz/bitcoin-core:24.0.1
    command: "-regtest -fallbackfee=0.00000253 -zmqpubrawtx=tcp://0.0.0.0:29000 -zmqpubrawblock=tcp://0.0.0.0:29001 -txindex -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=lnbits -rpcpassword=lnbits"
    expose:
      - 29000
      - 29001
      - 18443
      - 18444

  elementsd:
    hostname: elements
    image: ghcr.io/vulpemventures/elements:22.1.1
    expose:
      - 18884
      - 31000
      - 31001
      - 31002
    volumes:
      - ./data/elements:/home/elements/.elements

  clightning-1:
    hostname: clightning-1
    depends_on:
      - bitcoind
    image: boltz/c-lightning:22.11.1
    entrypoint: "sh -c 'sleep 15 && lightningd --large-channels --network regtest --bind-addr=0.0.0.0:9735 --bitcoin-rpcconnect=bitcoind --bitcoin-rpcport=18443 --bitcoin-rpcuser=lnbits --bitcoin-rpcpassword=lnbits'"
    expose:
      - 9735
    volumes:
      - ./data/clightning-1:/root/.lightning/

  lnd-1:
    hostname: lnd-1
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.5-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd-1:9735 --rpclisten=lnd-1:10009 --restlisten=lnd-1:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=lnbits --bitcoind.rpcpass=lnbits --noseedbackup --protocol.wumbo-channels'"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-1:/root/.lnd/

  lnd-2:
    hostname: lnd-2
    depends_on:
      - bitcoind
    image: boltz/lnd:0.15.5-beta
    restart: on-failure
    entrypoint: "sh -c 'sleep 20; lnd --listen=lnd-2:9735 --rpclisten=lnd-2:10009 --restlisten=lnd-2:8081 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind --bitcoind.zmqpubrawtx=bitcoind:29000 --bitcoind.zmqpubrawblock=bitcoind:29001 --bitcoind.rpcuser=lnbits --bitcoind.rpcpass=lnbits --noseedbackup --protocol.wumbo-channels'"
    expose:
      - 8081
      - 9735
      - 10009
    volumes:
      - ./data/lnd-2:/root/.lnd/

  electrs:
    depends_on:
      - bitcoind
    hostname: electrs
    image: getumbrel/electrs:latest
    environment:
      ELECTRS_ELECTRUM_RPC_ADDR: "electrs:50001"
      ELECTRS_DAEMON_RPC_ADDR: "bitcoind:18443"
      ELECTRS_DAEMON_P2P_ADDR: "bitcoind:18444"
    entrypoint: "sh -c 'sleep 15 && electrs'"
    ports:
      - 50001:50001
    volumes:
      - ./data/electrs/:/data/.electrs/

  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    hostname: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-rpc-addr
      - elementsd:18884
      - --cookie
      - lnbits:lnbits
      - --http-addr
      - 0.0.0.0:30001
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      - elementsd
    expose:
      - 50001:50001
      - 30001:30001

  mempool-web:
    restart: on-failure
    depends_on:
      - mempool-api
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    image: mempool/frontend:latest
    ports:
      - 8090:8080

  mempool-api:
    depends_on:
      - electrs
      - mempool-db
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: electrs
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: bitcoind
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "lnbits"
      CORE_RPC_PASSWORD: "lnbits"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    restart: on-failure

  mempool-api-liquid:
    depends_on:
      - electrs-liquid
      - mempool-db
    environment:
      MEMPOOL_NETWORK: "liquid"
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: electrs-liquid
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: elementsd
      CORE_RPC_PORT: "18884"
      CORE_RPC_USERNAME: "lnbits"
      CORE_RPC_PASSWORD: "lnbits"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool_liquid"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    restart: on-failure

  mempool-web-liquid:
    restart: on-failure
    depends_on:
      - mempool-api-liquid
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api-liquid"
    image: mempool/frontend:latest
    ports:
      - 8091:8080

  mempool-db:
    environment:
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS mempool; CREATE DATABASE IF NOT EXISTS mempool_liquid; GRANT ALL ON *.* TO 'mempool';' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

volumes:
  lnbits-data:
