name: ci
on: [push, pull_request]
jobs:
  regtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          chmod +x ./tests
          ./tests
