name: ci
on: [push, pull_request]
jobs:
  regtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          git clone https://github.com/lnbits/lnbits-legend
          cd lnbits-legend
          docker build -t lnbits-legend .
          cd ..
          chmod +x ./tests
          ./tests
